on: [push, pull_request]
name: Continous Integration
jobs:
  check_tests_ubuntu:
    name: Check Tests (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: run
        uses: ngalaiko/bazel-action/1.1.0@master
        with:
          args: test //... --test_output=all

  check_tests_osx:
    name: Check Tests (Mac OS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master

      - name: Install bazel
        run: |
          curl -L -O "https://github.com/bazelbuild/bazel/releases/download/1.1.0/bazel-1.1.0-installer-darwin-x86_64.sh"
          chmod a+x ./bazel-1.1.0-installer-darwin-x86_64.sh
          ./bazel-1.1.0-installer-darwin-x86_64.sh

      - name: run
        run: bazel test //... --test_output=all
    
  check_formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1

      - name: Install clang
        run: |
          wget "http://releases.llvm.org/9.0.0/clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz" -O clang.tar.xz
          tar xf clang.tar.xz
          cd clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-18.04
          sudo cp -R * /usr/local
          cd ..
          rm -rf clang+llvm-9.0.0-x86_64-linux-gnu-ubuntu-18.04

      - name: Instal yapf and pyling
        run: |
          pip install yapf
          pip install pylint

      - name: Run Check Script
        run: ./check-format.sh
